# Generated by Django 2.1.5 on 2019-02-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
