# Generated by Django 2.1.5 on 2019-02-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
